#!/usr/bin/env python
#******************************************************************************
#  Name:  ingestsar.py
#  Purpose:
#    utility to ingest georeferenced quadpol radarsat-2
#    files generated by Sentinel-1 toolbox and 
#    convert to a single 9-band float32 image.
#
#   Usage:
#   import ingestrs2
#   ingestrs2.ingest(path)
#        or
#   python ingestrs2.py [-h] indir
#
# MIT License
# 
# Copyright (c) 2016 Mort Canty
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import os, re, sys, getopt, time
import numpy as np
from osgeo import gdal
from osgeo.gdalconst import GA_ReadOnly, GDT_Float32

def ingest(path):    
    print '========================='
    print '     Ingest SAR'
    print '========================='
    print time.asctime()  
    print 'Directory %s'%path 
    
    start = time.time()
    path1 = path+'/polsarpro/T3/'
    try:
    #  get sorted list of covariance matrix element files    
        files1 = os.listdir(path1)
        files = []
        for afile in files1:
            if re.search('T[1-3]{2}',afile) and not re.search('hdr',afile): # coherency matix format
                files.append(afile)
        files.sort()        
        bands = len(files)
    #  get real and imaginary in right order    
        tmp = files[1]
        files[1] = files[2]
        files[2] = tmp
        tmp = files[3]
        files[3] = files[4]
        files[4] = tmp
        tmp = files[6]
        files[6] = files[7]
        files[7] = tmp
    #  get image dimensions
        outfn = path+'polSAR.tif'
        gdal.AllRegister()   
        inDataset = gdal.Open(path1+files[0],GA_ReadOnly)
        cols = inDataset.RasterXSize
        rows = inDataset.RasterYSize       
    #  create the output file
        driver = gdal.GetDriverByName('GTiff') 
        outDataset = driver.Create(outfn,cols,rows,bands,GDT_Float32)
        projection = inDataset.GetProjection()
        geotransform = inDataset.GetGeoTransform()
        if geotransform is not None:
            outDataset.SetGeoTransform(geotransform)
        if projection is not None:
            outDataset.SetProjection(projection)
        inDataset = None     
    #  ingest
        for i in range(bands):
            print 'writing band %i'%(i+1)
            inDataset = gdal.Open(path1+files[i])
            inBand = inDataset.GetRasterBand(1)
            band = inBand.ReadAsArray(0,0,cols,rows).astype(np.float32)
            outBand = outDataset.GetRasterBand(i+1)
            outBand.WriteArray(band)
            outBand.FlushCache()
            inDataset = None
        outDataset = None
        print 'elapsed time: ' + str(time.time() - start)
        return outfn
    except Exception as e:
        print 'Error %s  --Image could not be read in'%e 
        return None     
     
    
def main():
    usage = '''
Usage:
------------------------------------------------

python %s [OPTIONS] indir

Options:

   -h     this help

indir: directory containing the geo-referenced and terrain-corrected
polarimetric covariance matrix elements (as generated by MapReady).

------------------------------------------------''' %sys.argv[0]

    options, args = getopt.getopt(sys.argv[1:],'h')  
    for option, _ in options:
        if option == '-h':
            print usage
            return        
    if len(args) != 1:
        print 'Incorrect number of arguments'
        print usage
        sys.exit(1)  
    os.chdir(args[0])
    if os.path.isfile('polSAR.tif'):
        print 'Overwriting previous combined image'
    outfn = ingest(args[0])
    if outfn is not None:
        print 'Multiband image is %s'%outfn
    
if __name__ == '__main__':
    main()
    